Add channel order param to preprocessing tests.
These tests were not passing due to a change introduced in 2dd2efb which
added a parameter to the function get_input_tensors, but did not update
the tests.

Note that there is still a single failing test that I have not
investigated:

```
======================================================================
FAIL: test_rotate_pyfunc (tests.test_preprocessing.TestPreprocessing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./tests/test_preprocessing.py", line 194, in test_rotate_pyfunc
    self.assert_rotate_data(run_one, run_two, run_three)
  File "./tests/test_preprocessing.py", line 128, in assert_rotate_data
    self.assertEqual(set(), difference, "Didn't find these rotations")
AssertionError: Items in the second set but not the first:
'flip' : Didn't find these rotations
```